---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by newmaster.
--- DateTime: 2024/6/30 下午2:24
---

-- 参数列表
-- 1.1优惠券id
local voucherId = ARGV[1]

-- 1.2用户id
local userId = ARGV[2]

-- 1.3订单ID
local orderId = ARGV[3]

-- 2.数据key
-- 2.1.库存key
local stockKey = 'seckill:stock:' .. voucherId
-- 2.2.订单key
local orderKey = 'seckill:order:' .. voucherId

-- 3.脚本业务
-- 3.1.判断库存是否充足 get stockKey,tonumber关键字用于将返回的字符串类型转换为数值类型
if(tonumber(redis.call('get', stockKey)) <= 0) then
    -- 3.2.库存不足，返回1
    return 1
end

-- 3.2判断一人一单业务 SISMEMBER orderKey userId
if (redis.call('sismember', orderKey, userId) == 1) then
    -- 存在,说明是重复下单,不允许,返回2
    return 2
end

-- 3.3扣除库存
redis.call('incrby', stockKey, -1)

-- 3.4下单(保存用户)
redis.call('sadd', orderKey, userId)

-- 3.5 发送消息到消息队列中 XADD stream.orders * k1 v1 k2 v2 ...
-- redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)

return 0
